name: "Stale"
on:
  schedule:
    - cron: "30 1 */4 * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "Esta issue est치 inativa h치 60 dias. Marque como 'fresco' ou comente para reativar."
          stale-pr-message: "Este PR est치 inativo h치 60 dias. Marque como 'fresco' ou comente para reativar."
          close-issue-message: "Esta issue foi fechada por inatividade."
          close-pr-message: "Este PR foi fechado por inatividade."
          days-before-issue-stale: 60
          days-before-pr-stale: 60
          days-before-issue-close: 7
          days-before-pr-close: 7
          exempt-issue-labels: "security,bug,enhancement,pinned,long-term"
          exempt-pr-labels: "security,bug,enhancement,pinned,long-term"
